services:
  web:
    image: golang:1.21.6
    ports:
      - ${APP_PORT}:80
    environment:
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
    volumes:
      - ./web/:/app
    working_dir: /app
    command: bash -c "go run ."
    restart: always
    networks:
      - app-net

  db:
    container_name: mysql-db
    image: mysql:9.0
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOTPASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    restart: always
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-store:
