info:
  contact: {}
  description: 位置情報と連携したリマインダーアプリに使用するAPIです
  license:
    name: MIT License
    url: https://opensource.org/license/mit
  title: GPS Reminder API
  version: Beta
paths: {}
swagger: "2.0"
